- name: Build & Push Docker Image
  uses: docker/build-push-action@v5
  with:
    context: .
    file: ./apps/dashboard/Dockerfile
    push: true
    tags: |
      ${{ secrets.DOCKER_HUB_USERNAME }}/edge-app:latest
      ${{ secrets.DOCKER_HUB_USERNAME }}/edge-app:${{ github.sha }}
